#!/bin/sh /etc/rc.common

START=80
NAME="aliddns"
EXTRA_COMMANDS="status"
EXTRA_HELP="        status          Service status"

NE_TIPS="AliDDNS NOT ENABLED"

restart() {
	start
}

uci_get_by_name() {
	local ret
	ret="$(uci get "${NAME}.$1.$2" 2>/dev/null)"
	echo "${ret:-$3}"
}

uci_bool_by_name() {
	case "$(uci_get_by_name "$1" "$2")" in
		1 | on | true | yes | enabled) return 0 ;;
	esac
	return 1
}

add_hotplug() {
	cat <<'HOTPLUG_EOF' > "/etc/hotplug.d/iface/${START}-${NAME}"
#!/bin/sh /etc/rc.common

[ "Z${ACTION}" = "Zifup" -a "Z${INTERFACE}" = "Zwan" ] || exit 0

DATE=$(date +'%Y-%m-%d %H:%M:%S')
( sleep 10 && ( echo "${DATE} IFUP-WAN" && /usr/sbin/aliddns ) >> /var/log/aliddns.log 2>&1 ) &

exit 0
HOTPLUG_EOF
	chmod +x "/etc/hotplug.d/iface/${START}-${NAME}"
}

start() {
	uci_bool_by_name base enable || {
		stop
		return 0
	}

	add_hotplug

	sed -i "/${NE_TIPS}/d" /var/log/aliddns.log

	local time_interval
	time_interval="$(uci_get_by_name base time 10)"
	if [ -z "$time_interval" ]; then
		time_interval=10
	fi
	if [ "$time_interval" -lt 1 ] || [ "$time_interval" -gt 59 ]; then
		time_interval=10
	fi

	[ -f /etc/crontabs/root ] || { mkdir -p /etc/crontabs && touch /etc/crontabs/root; }
	sed -i '/aliddns/d' /etc/crontabs/root
	echo "*/${time_interval} * * * * /usr/sbin/aliddns >> /var/log/aliddns.log 2>&1" >> /etc/crontabs/root
	if [ "$(/etc/init.d/cron status 2>/dev/null)" = "running" ]; then
		/etc/init.d/cron reload
	fi

	/usr/sbin/aliddns >> /var/log/aliddns.log 2>&1 &
}

stop() {
	rm -f "/etc/hotplug.d/iface/${START}-${NAME}"
	sed -i '/aliddns/d' /etc/crontabs/root >/dev/null 2>&1
	if [ "$(/etc/init.d/cron status 2>/dev/null)" = "running" ]; then
		/etc/init.d/cron reload
	fi
	echo "${NE_TIPS}" > /var/log/aliddns.log
}

status() {
	if [ "$(/etc/init.d/cron status 2>/dev/null)" != "running" ]; then
		echo "inactive"
		return 1
	else
		if grep -q aliddns /etc/crontabs/root 2>/dev/null; then
			echo "running"
		else
			echo "inactive"
			return 1
		fi
	fi
}
